### ISSUE TITLE
About the path "./results_pretrained/" in the evaluation code

### ISSUE THREAD

**Issue by KVBK01** [wei-mao-2019/gsps#2]
Thanks for you wonderful work and code!
I have a question about the path "./results_pretrained/" in the evaluation code. 

in the eval.py, line 484, it says
cp_path = './results_pretrained/h36m_linNF_pose_prior_float/models/vae_0025.p' if cfg.dataset == 'h36m' else \
           ​'./results_pretrained/humaneva_nf/models/vae_0025.p'

But your provided code does not contain a "results_pretrained" folder. I am wondering, do I need to train again and then make my own "results_pretrained" to run the evaluation code? 

I would appreciate it very much if you could reply!

**Comment by wei-mao-2019** [comment]
Thank you for pointing it out.

It should be cp_path = './results/h36m_linNF_pose_prior_float/models/vae_0025.p'. I will update this.

**Comment by KVBK01** [comment]
> Thank you for pointing it out.
> 
> It should be cp_path = './results/h36m_linNF_pose_prior_float/models/vae_0025.p'. I will update this.

Thanks for your kind reply! 
But your provided "results" folder also does not contain a "h36m_linNF_pose_prior_float" subfolder...
Maybe it should be the "./results/h36m_nf" folder ?

**Comment by wei-mao-2019** [comment]
Yes, you are right. It has been updated.
